drafts/25-revise-24-177 Fortran preprocessor requirements.txt
A cpp-like preprocessor was proposed in 1995-1996
but lost out to the more Fortran-like CoCo
preprocessor. It's fun to see our new discussions
in that context.
=> Add more references, going back in time to discussions in 1990s

drafts/25-revise-24-177 Fortran preprocessor requirements.txt
Add #warning to the list of supported directives
`#warning` was standardized in C23/C++23 after being widely implemented
for years, and there seems to be consensus that Fortran's preprocessor
should also have it.
This notably enables a standardized mechanism for issuing
coarse-granularity deprecation messages during compilation.
Resolves #7
=> Add #warning

drafts/25-revise-24-177 Fortran preprocessor requirements.txt
There has been significant (and well-founded) pushback on the `__STDF_VERSION__` predefined macro proposed in 24-177, on the basis that it's too coarse-grained to ever be reliably useful as a language feature test in practice. We should remove it.
There has also been confusion over the purpose of the proposed `__STDF__`, so we should clarify that. 
Resolves #9
=> Remove __STDF_VERSION__ and clarify __STDF__

drafts/25-revise-24-177 Fortran preprocessor requirements.txt
One line in the References is too long. wrap to the next line.
Also noticed a line with extraneous blanks at the end. Delete those.
=> NFC: break long line; delete extra blanks

drafts/25-revise-24-177 Fortran preprocessor requirements.txt
Change all preprocessor expressions for #if, #elif to evaluate to integer values. Define the relationship of Fortran logical constants and operators to their C counterparts.
Addresses #14.
=> Add more rules on preprocessor expressions and their types

drafts/25-revise-24-177 Fortran preprocessor requirements.txt
Add context from papers from the 1990s.
Mention CoCo in Fortran 95 as not solving the problem. Emphasize the portability issues beyond simple use cases.
=> Expand the introductory text

drafts/25-revise-24-177 Fortran preprocessor requirements.txt
Add authorship.
Limit line lengths and re-wrap paragraphs.
Ensure two blank line before headings for visibility. 
Remove blank lines after headings for consistency. 
Remove two spaces after period for consistency.
Add indentation for predefined macro names for readability.
=> Final text cleanup before upload to J3 web site

drafts/25-114.txt
This adds the five-ish operators accepted by CPP in `#if` and `#elif` that were missing from 25-114r0.
Also rearrange/regroup the operator list and add explanatory parentheticals, for readers less familiar with C grammar. I assume a future syntax paper will explode this out further to show the full grammar, but that seems redundant for requirements and I think this conveys the right intuition without being too pedantic.
Resolves issue #33
=> Add all the operators that CPP allows in #if / #elif expressions

drafts/25-114.txt
After discussion, remove prohibition on expansion in `FORMAT` specifications, and `IMPLICIT` statements. Also, treat Hollerith data and format specifiers as we treat character constants.
=> No expansion: remove mention of FORMAT and IMPLICIT

drafts/25-114.txt
CPP _recognizes_ and processes certain tokens (`#`, `##`, `__VA_ARGS__`, `__VA_OPT__`, and FLM arguments), in the replacement-list of macro. But it never "rejects" anything whatsoever, any unrecognized tokens are just passed through uninterpreted to expansion. So it's not correct to talk about "accepting tokens" in that context.
`__VA_ARGS__`, `__VA_OPT__` really belong in this section instead of "4.4 Macros defined by the preprocessor" where they were misleadingly placed before, so move them.
=> Rename section 4.2 and move __VA_*

drafts/25-114.txt
After discussion today, JoR subgroup agreed that we had no strong use cases for adding Fortran relational and logical operators to the Fortran preprocessor. Such operators do not appear with any frequency in our corpus of example Fortran projects.
We agreed to limit the operators used to construct #if and #elif expressions to those available in the C preprocessor for constructing constant expressions.
Fixes #38.
=> Remove references to Fortran operators and constants

drafts/25-114.txt
- Parenthesize C 23 working draft version.
- Clip line lengths.
- Increase indentation on list of Fortran operators to make it stand out from the body text.
- Fix inconsistent lack of `:` on fixed-form non-expansion list.
=> Final cleanup before uploading 25-114r1

drafts/25-114.txt
Remove a left-over parenthetical statement, which was rendered obsolete with the merge of PR #39.
FPP expressions for #if and #elif no longer accept a superset of operators accepted by CPP (it's now a proper subset).
=> Remove obsolete parenthetical

wg5-papers/N2234 Work items from the hybrid wg5 meeting 2024-06.txt
To put a stake in the ground, WG 5 voted in their June 2024 meeting #43 to include a CPP-like preprocessor in the approved work item list for Fortran 202y. It is item US10.
=> Add WG 5 paper with approval of preprocessor to 2028 work list

drafts/25-114.txt
We no longer try to discern "comment directives" for macro expansion. A simpler proposal to expand in (full-line) comment lines is added.
A proposal to mention no token expansion in "alternative syntax for character constants and edit descriptors" was added. (We're looking at you, Hollerith.)
Add reference for the Fortran 2023 Interpretation document, 24-007, as we use it to define "comment line" meaning a comment that contains all the non-blank portion of a line.
=> Expand in only full-line comments; don't expand in alternative chars

drafts/25-xxx-specifications.txt
Many subsections are not filled in yet.
At the end is a bunch of raw material that we
need to consider adding to the earlier sections.
This raw material comes from 25-114r2, Peter Klausler's Preprocessing.md in Flang, and Berkely Lab's
assert library.There are probably other places
we need to pull from as well.
=> Add initial (very rough) outline for specifications paper

drafts/25-xxx-specifications.txt
- Renumber spec lists a bit to get unique numbers and allow for insert additional specifications a bit more easily.
- Collapse original section 2 "Formal specifications" into its main "Lexical specifications" to include lines, whitespace, etc.
- Add Patrick Fasano comments on multiple whitespace characters (but be explicit about it being in non-character-constant contexts).
- Remove the over-specified list of tokens. This is more appropriate for a syntax paper. Introduce tokens enough to allow us to use them in illustrative syntax. (We can remove the explicitness about the tokens `ID`, `WHOLE_NUMBER`, `REAL_NUMBER`, `CHARACTER_STRING`, and `UNRECOGNIZED_TOKEN` if we like.)
=> Update section 2 with several additions for review

drafts/25-xxx-specifications.txt
These are heavily based on specification prose in C23, with adjustments to match the terminology of the Fortran spec and this draft.
=> Add specifications for predefined macros

drafts/25-xxx-specifications.txt
=> macros: Reserve (some) macros beginning with underscore to the implementation

drafts/25-xxx-specifications.txt
Creates an appendix documenting deliberate divergences from CPP.
Some of these entries are speculative and reflect my understanding of our current consensus, even though the corresponding specifications have not yet been written or merged into the earlier sections. If I'm incorrect and any of the listed differences prove contentious, then I'd prefer to drop the contentious point from this PR and take any unresolved semantic discussions to the issue tracker or PRs on earlier sections.
Fixes #66
=> issue #66: Create an appendix documenting deliberate divergences from CPP

drafts/25-xxx-specifications.txt
Initial draft of Section 3.5. Added illustrative syntax, static semantics and evaluation semantics, up to but not including controlling expression evaluation. (That will be an another section.)
I tried to use the terminology from the C 2023 standard, but reviewers will surely find lapses and potential improvements.
=> Rough draft of Section 3.5 conditionals: #if, #elif, etc.

drafts/25-xxx-specifications.txt
This is analogous to CPP 6.10.8, which reserves `#pragma STDC` for use in standardized pragmas.
=> Reserve `#pragma STDF`
